---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-example-deployment
  labels:
    app: basic-example
    type: front-end
spec:
  template:
    metadata:
      name: basic-example-pod
      labels:
        app: basic-example
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginxdemos/hello
  replicas: 6
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: basic-example-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30000
  selector:
    app: basic-example
    type: front-end
